### ISSUE TITLE
js逆向

### ISSUE THREAD

**Issue by dmf-code** [CriseLYJ/Python-crawler-tutorial-starts-from-zero#12]
作者你好，js逆向什么时候出呀？有交流的QQ群吗？

**Comment by Dustyposa** [comment]
@dmf-code 
您好， 目前还没有交流群和逆向，原作者近两天比较忙，我们正在重新规划整个体系，以帮助学习者更好的掌握知识。
您现在遇到了问题的话，可以在这里利用 issue 提出。
QQ群的话我告知一下原作者。

**Comment by Kr1s77** [comment]
@dmf-code 已经上传，百度翻译
