### ISSUE TITLE
建议作者能够给出一个更新计划, 或者说更新列表, 不然不好确定当前更新到了什么地步

### ISSUE THREAD

**Issue by lartpang** [CriseLYJ/Python-crawler-tutorial-starts-from-zero#8]

**Comment by jayzhan211** [comment]
他目前出的就是最新的阿 按照順序的

**Comment by lartpang** [comment]
其实我的issue更想要强调的是"更新计划". 因为读者并不知道作者准备怎么写下去, 该有怎样的期待, 这也会影响着读者继续关注的动力, 等等, 我觉得对于这个项目而言, 一个清晰地更新计划或许会更好一些. 

您觉得呢?

**Comment by Kr1s77** [comment]
@lartpang 我觉得可以写一下  更新的大致计划吧！

但是我想添加一些更有意思的东西进去，所以我需要重新规划一下！
